#!/usr/bin/env bash
# ==============================================================================
# sync-env.sh - Dong bo Terraform outputs vao frontend .env file
# ==============================================================================
# CACH SU DUNG:
#   cd terraform
#   chmod +x scripts/sync-env.sh
#   ./scripts/sync-env.sh
#
# Script nay:
#   1. Doc terraform output (api_url, website_url, etc.)
#   2. Tao/ghi de file .env tai root du an
#   3. Hien thi thong tin deploy
#
# YEU CAU: Da chay terraform apply thanh cong
# ==============================================================================

set -euo pipefail

OUTPUT_FILE="${1:-../.env}"
DRY_RUN="${DRY_RUN:-false}"

echo ""
echo "======================================"
echo "  Coffee Shop - Sync Terraform -> .env"
echo "======================================"
echo ""

# Kiem tra dang o trong thu muc terraform
if [ ! -f "providers.tf" ]; then
    echo "[ERROR] Khong tim thay providers.tf. Hay chay script tu thu muc terraform/"
    echo "  cd terraform"
    echo "  ./scripts/sync-env.sh"
    exit 1
fi

# Doc cac outputs
echo "[1/3] Doc terraform outputs..."

API_URL=$(terraform output -raw api_url 2>/dev/null || echo "")
WEBSITE_URL=$(terraform output -raw website_url 2>/dev/null || echo "")
FRONTEND_BUCKET=$(terraform output -raw frontend_bucket_name 2>/dev/null || echo "")
IMAGES_BUCKET=$(terraform output -raw images_bucket_name 2>/dev/null || echo "")

if [ -z "$API_URL" ]; then
    echo "[ERROR] api_url output rong. Hay chay 'terraform apply' truoc."
    exit 1
fi

# Tao noi dung .env
ENV_CONTENT="# ==============================================================================
# Frontend Environment Variables
# ==============================================================================
# Auto-generated by sync-env.sh from Terraform outputs
# Generated at: $(date '+%Y-%m-%d %H:%M:%S')
#
# KHONG EDIT FILE NAY TRUC TIEP!
# Sua Terraform config va chay lai: terraform apply && ./scripts/sync-env.sh
# ==============================================================================

# API Gateway URL (tu Terraform output)
VITE_API_BASE_URL=${API_URL}"

echo "[2/3] Tao file .env..."

if [ "$DRY_RUN" = "true" ]; then
    echo ""
    echo "--- DRY RUN - Noi dung se ghi vao $OUTPUT_FILE ---"
    echo "$ENV_CONTENT"
    echo "--- END DRY RUN ---"
else
    echo "$ENV_CONTENT" > "$OUTPUT_FILE"
    echo "  -> Ghi thanh cong: $OUTPUT_FILE"
fi

# Hien thi thong tin
echo ""
echo "[3/3] Thong tin deploy:"
echo ""
echo "  API URL:          $API_URL"
echo "  Website URL:      $WEBSITE_URL"
echo "  Frontend Bucket:  $FRONTEND_BUCKET"
echo "  Images Bucket:    $IMAGES_BUCKET"
echo ""
echo "======================================"
echo "  BUOC TIEP THEO:"
echo "======================================"
echo ""
echo "  1. Build frontend:"
echo "     cd .. && npm run build"
echo ""
echo "  2. Deploy len S3:"
echo "     aws s3 sync dist/ s3://$FRONTEND_BUCKET"
echo ""
echo "  3. Truy cap website:"
echo "     $WEBSITE_URL"
echo ""
