# ==============================================================================
# sync-env.ps1 - Dong bo Terraform outputs vao frontend .env file
# ==============================================================================
# CACH SU DUNG:
#   cd terraform
#   .\scripts\sync-env.ps1
#
# Script nay:
#   1. Doc terraform output (api_url, website_url, etc.)
#   2. Tao/ghi de file .env tai root du an
#   3. Hien thi thong tin deploy
#
# YEU CAU: Da chay terraform apply thanh cong
# ==============================================================================

param(
    [string]$OutputFile = "..\\.env",
    [switch]$DryRun
)

Write-Host ""
Write-Host "======================================" -ForegroundColor Cyan
Write-Host "  Coffee Shop - Sync Terraform -> .env" -ForegroundColor Cyan
Write-Host "======================================" -ForegroundColor Cyan
Write-Host ""

# Kiem tra dang o trong thu muc terraform
if (-not (Test-Path "providers.tf")) {
    Write-Host "[ERROR] Khong tim thay providers.tf. Hay chay script tu thu muc terraform/" -ForegroundColor Red
    Write-Host "  cd terraform" -ForegroundColor Yellow
    Write-Host "  .\scripts\sync-env.ps1" -ForegroundColor Yellow
    exit 1
}

# Kiem tra terraform state
if (-not (Test-Path "terraform.tfstate") -and -not (Test-Path ".terraform")) {
    Write-Host "[ERROR] Chua co terraform state. Hay chay 'terraform apply' truoc." -ForegroundColor Red
    exit 1
}

# Doc cac outputs
Write-Host "[1/3] Doc terraform outputs..." -ForegroundColor Yellow

try {
    $apiUrl = terraform output -raw api_url 2>$null
    $websiteUrl = terraform output -raw website_url 2>$null
    $frontendBucket = terraform output -raw frontend_bucket_name 2>$null
    $imagesBucket = terraform output -raw images_bucket_name 2>$null
} catch {
    Write-Host "[ERROR] Khong the doc terraform outputs. Hay chay 'terraform apply' truoc." -ForegroundColor Red
    exit 1
}

if (-not $apiUrl) {
    Write-Host "[ERROR] api_url output rong. Hay chay 'terraform apply' truoc." -ForegroundColor Red
    exit 1
}

# Tao noi dung .env
$envContent = @"
# ==============================================================================
# Frontend Environment Variables
# ==============================================================================
# Auto-generated by sync-env.ps1 from Terraform outputs
# Generated at: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
#
# KHONG EDIT FILE NAY TRUC TIEP!
# Sua Terraform config va chay lai: terraform apply && .\scripts\sync-env.ps1
# ==============================================================================

# API Gateway URL (tu Terraform output)
VITE_API_BASE_URL=$apiUrl
"@

Write-Host "[2/3] Tao file .env..." -ForegroundColor Yellow

if ($DryRun) {
    Write-Host ""
    Write-Host "--- DRY RUN - Noi dung se ghi vao $OutputFile ---" -ForegroundColor Magenta
    Write-Host $envContent
    Write-Host "--- END DRY RUN ---" -ForegroundColor Magenta
} else {
    $envContent | Out-File -FilePath $OutputFile -Encoding utf8 -NoNewline
    Write-Host "  -> Ghi thanh cong: $OutputFile" -ForegroundColor Green
}

# Hien thi thong tin
Write-Host ""
Write-Host "[3/3] Thong tin deploy:" -ForegroundColor Yellow
Write-Host ""
Write-Host "  API URL:          $apiUrl" -ForegroundColor White
Write-Host "  Website URL:      $websiteUrl" -ForegroundColor White
Write-Host "  Frontend Bucket:  $frontendBucket" -ForegroundColor White
Write-Host "  Images Bucket:    $imagesBucket" -ForegroundColor White
Write-Host ""
Write-Host "======================================" -ForegroundColor Cyan
Write-Host "  BUOC TIEP THEO:" -ForegroundColor Cyan
Write-Host "======================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "  1. Build frontend:" -ForegroundColor White
Write-Host "     cd .. && npm run build" -ForegroundColor Yellow
Write-Host ""
Write-Host "  2. Deploy len S3:" -ForegroundColor White
Write-Host "     aws s3 sync dist/ s3://$frontendBucket" -ForegroundColor Yellow
Write-Host ""
Write-Host "  3. Truy cap website:" -ForegroundColor White
Write-Host "     $websiteUrl" -ForegroundColor Yellow
Write-Host ""
# aws s3 sync dist/ s3://coffee-shop-frontend-hoangcon --delete --cache-control "no-cache, no-store, must-revalidate"