name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@3.0.50.73 << EOF

            # 1) Kiểm tra đã có docker và docker-compose chưa, nếu chưa có thì cài đặt
            if ! command -v docker &> /dev/null; then
              echo "Docker not found, installing..."
              sudo apt-get update
              sudo apt-get install -y docker.io
            fi

            if ! command -v docker-compose &> /dev/null; then
              echo "Docker Compose not found, installing..."
              sudo apt-get install -y docker-compose
            fi

            # 2) Tải mã nguồn từ GitHub về
            cd ~
            if [ ! -d "Serverless-web" ]; then
              git clone https://github.com/imLeHuyHoang/Serverless-web.git
              cd Serverless-web
            else
              cd Serverless-web
              git pull origin main
            fi

            # 3) Cài đặt Node.js và npm phiên bản 20.x 
            if ! command -v node &> /dev/null; then
              echo "Node.js not found, installing..."
              curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi

            # 4) Cài đặt các thư viện cần thiết
            npm install

            # 5) Chạy npm run test 
            CI=true npm run test

            # 6) Dừng & xoá container cũ (nếu có)
            sudo docker-compose down --rmi all --volumes --remove-orphans || true

            # 7) Build & chạy lại container
            echo "Starting Docker containers..."
            sudo docker-compose up -d --build



          EOF
